// Target layout from architecture-review/website-information-architecture.md.
// Explicit routes keep the menu stable while individual pages are written.
export const sidebar = [
  { label: 'Start here', items: [
    { label: 'Overview', slug: 'docs' },
    { label: 'Make your first request', slug: 'docs/first-request' },
  ] },
  { label: 'Connect', items: [
    { label: 'Connect a provider', slug: 'docs/providers' },
    { label: 'Connect a local or custom server', slug: 'docs/custom-servers' },
    { label: 'Set up authentication', slug: 'docs/authentication' },
    { label: 'Choose a model', slug: 'docs/models' },
  ] },
  { label: 'Cloud providers', items: [
    { label: 'Use Google Cloud (Vertex AI)', slug: 'docs/google-cloud' },
  ] },
  { label: 'Use tools', items: [
    { label: 'Call your own functions', slug: 'docs/function-tools' },
    { label: 'Use provider tools', slug: 'docs/provider-tools' },
  ] },
  { label: 'Generate responses', items: [
    { label: 'Keep a conversation', slug: 'docs/conversations' },
    { label: 'Stream a response', slug: 'docs/streaming' },
    { label: 'Control generation', slug: 'docs/generation' },
    { label: 'Work with reasoning models', slug: 'docs/reasoning' },
    { label: 'Get structured output', slug: 'docs/structured-output' },
    { label: 'Ask for judgments with probabilities', slug: 'docs/judgments' },
    { label: 'Send images and documents', slug: 'docs/media-inputs' },
    { label: 'Cache prompts', slug: 'docs/prompt-caching' },
  ] },
  { label: 'Build your app', items: [
    { label: 'Handle errors and retries', slug: 'docs/errors-and-retries' },
    { label: 'Test your integration', slug: 'docs/testing' },
    { label: 'Run in the browser', slug: 'docs/browser' },
    { label: 'Migrate from an OpenAI-shaped client', slug: 'docs/migration' },
  ] },
  { label: 'Other APIs', items: [
    { label: 'Generate images and speech', slug: 'docs/media-generation' },
    { label: 'Generate video', slug: 'docs/video' },
    { label: 'Manage files and batches', slug: 'docs/files-and-batches' },
    { label: 'Open a realtime session', slug: 'docs/realtime' },
  ] },
  { label: 'API reference', items: [
    { label: 'Overview', slug: 'reference' },
    { label: 'Requests, messages, and content', slug: 'reference/requests' },
    { label: 'Responses and usage', slug: 'reference/responses' },
    { label: 'Generation settings', slug: 'reference/generation' },
    { label: 'Tools', slug: 'reference/tools' },
    { label: 'Clients and routing', slug: 'reference/clients' },
    { label: 'Streaming', slug: 'reference/streaming' },
    { label: 'Errors', slug: 'reference/errors' },
    { label: 'Serialization', slug: 'reference/serialization' },
    { label: 'Compatibility policies', slug: 'reference/compatibility' },
    { label: 'Model information', slug: 'reference/models' },
    { label: 'Authentication and transports', slug: 'reference/transports' },
    { label: 'Other endpoint APIs', slug: 'reference/other-apis' },
  ] },
  { label: 'Compatibility', items: [
    { label: 'Feature coverage', slug: 'compatibility' },
    { label: 'Provider directory', items: [
      { label: 'Overview', slug: 'compatibility/providers' },
      { label: 'Anthropic', slug: 'compatibility/providers/anthropic' },
      { label: 'DeepInfra', slug: 'compatibility/providers/deepinfra' },
      { label: 'DeepSeek', slug: 'compatibility/providers/deepseek' },
      { label: 'Fireworks AI', slug: 'compatibility/providers/fireworks' },
      { label: 'Google Gemini', slug: 'compatibility/providers/gemini' },
      { label: 'Groq', slug: 'compatibility/providers/groq' },
      { label: 'Meta', slug: 'compatibility/providers/meta' },
      { label: 'Moonshot / Kimi', slug: 'compatibility/providers/moonshotai' },
      { label: 'OpenAI', slug: 'compatibility/providers/openai' },
      { label: 'OpenRouter', slug: 'compatibility/providers/openrouter' },
      { label: 'Parasail', slug: 'compatibility/providers/parasail' },
      { label: 'Together AI', slug: 'compatibility/providers/together' },
      { label: 'Z.AI', slug: 'compatibility/providers/zai' },
    ] },
    { label: 'Language and runtime support', slug: 'compatibility/languages' },
    { label: 'How we verify support', slug: 'compatibility/verification' },
  ] },
  { label: 'Project', items: [
    { label: 'About LM15', slug: 'about' },
    { label: 'Benchmarks', items: [
      { label: 'Overview', slug: 'benchmarks' },
      { label: 'Python', slug: 'docs/benchmarks/python' },
      { label: 'TypeScript on Node.js', slug: 'docs/benchmarks/node' },
      { label: 'Rust', slug: 'docs/benchmarks/rust' },
      { label: 'Go', slug: 'docs/benchmarks/go' },
    ] },
    { label: 'Releases', slug: 'releases' },
    { label: 'Shared contract', link: 'https://github.com/lm15-dev/lm15-contract' },
    { label: 'Contributing', slug: 'contributing' },
    { label: 'Report a bug', slug: 'support' },
    { label: 'Security', slug: 'security' },
  ] },
];
