/**
 * Write a pack's verified code as plain text for the writers:
 * docs-assets/<pack>/code.md, every recipe with the given prefix, in all six
 * languages (with a placeholder provider and model). Generated; do not edit.
 *
 *   node --experimental-strip-types scripts/docs-assets-code.ts structured-output so-
 */
import { writeFileSync } from 'node:fs';
import { RECIPES } from '../src/data/docs-examples.ts';

const [pack, prefix] = process.argv.slice(2);
if (!pack || !prefix) throw new Error('usage: docs-assets-code.ts <pack> <recipe prefix>');
const LANGUAGES = [['python', 'python'], ['typescript', 'ts'], ['rust', 'rust'], ['go', 'go'], ['r', 'r'], ['julia', 'julia']] as const;
const names = Object.keys(RECIPES).filter(name => name.startsWith(prefix));
const out = [
  `# ${pack}: the verified code`,
  '',
  'Generated by `scripts/docs-assets-code.ts`; do not edit. Each recipe is what',
  '`<DocsExample recipe="…" />` shows, in the language the reader picked. All of',
  'it has been run in six languages (`npm run test:docs-examples`). The model',
  'shown here, `provider:model`, is replaced by the reader\'s choice on the page.',
  '',
  `Recipes: ${names.map(n => `\`${n}\``).join(', ')}.`,
];
for (const name of names) {
  out.push('', `## \`${name}\``);
  for (const [language, fence] of LANGUAGES) {
    out.push('', `### ${language}`, '', '```' + fence, RECIPES[name as keyof typeof RECIPES]({ language, provider: 'provider', model: 'model' }).text, '```');
  }
}
writeFileSync(new URL(`../docs-assets/${pack}/code.md`, import.meta.url), out.join('\n') + '\n');
console.log(`wrote docs-assets/${pack}/code.md: ${names.length} recipes`);
