/**
 * The Rust the playground's code panel shows, written to
 * `examples/rust/src/main.rs`. That standalone crate depends on the pinned
 * SDK revision, so checking it proves each snippet compiles against the SDK.
 * `npm run rust:snippets` regenerates; `tests/provider_examples.test.ts`
 * refuses drift between the generator and the committed file.
 */

import { writeFileSync } from "node:fs";
import { resolve } from "node:path";
import { fileURLToPath } from "node:url";
import { Message, continuationState, thinking } from "lm15/browser";
import { CONNECTIONS } from "../src/playground/connections.ts";
import { DEFAULT_SETTINGS, exampleRust, type Connection, type Settings } from "../src/playground/experience.ts";

export const rustExamplesPath = resolve(fileURLToPath(new URL("..", import.meta.url)), "examples", "rust", "src", "main.rs");

const FULL: Settings = { system: "Answer briefly.", temperature: 0.2, maxTokens: 64, reasoning: "low" };
const prompt = 'Quotes " and a newline\n</script> are text, not executable code.';

export function renderRustExamples(): string {
  const history = [
    Message.user("Earlier question"),
    Message.assistant([thinking("Earlier hidden reasoning", { continuation: [continuationState("anthropic", "thinking_signature", { signature: "opaque-replay-signature" })] }), "Earlier answer"]),
  ];
  const parts: string[] = [
    "//! The playground's Rust snippets (website/src/playground), one",
    "//! function each, so `cargo check --examples` proves the code the page",
    "//! shows compiles against this crate. Generated by",
    "//! `npm run rust:snippets` in website; do not edit by hand. Nothing here",
    "//! runs: `main` never calls these (they would need keys and a network).",
    "#![allow(dead_code, unused_variables, unused_mut, clippy::all)]",
    "",
  ];
  for (const choice of CONNECTIONS) {
    for (const [suffix, messages, settings] of [["first_turn", [], DEFAULT_SETTINGS], ["with_history", history, FULL]] as const) {
      const connection: Connection = { provider: choice.id, model: choice.model || "custom-model", endpoint: "http://localhost:1234/v1" };
      const body = exampleRust(connection, settings, messages, prompt);
      const [uses, code] = splitUses(body);
      parts.push(`mod ${choice.id.replace(/-/g, "_")}_${suffix} {`, ...uses.map((u) => `    ${u}`), "", "    pub async fn run() -> Result<(), Box<dyn std::error::Error>> {", ...code.split("\n").map((line) => (line ? `        ${line}` : "")), "        Ok(())", "    }", "}", "");
    }
  }
  parts.push("fn main() {}", "");
  return parts.join("\n");
}

function splitUses(source: string): [string[], string] {
  const lines = source.split("\n");
  const uses = lines.filter((l) => l.startsWith("use "));
  const rest = lines.filter((l) => !l.startsWith("use ")).join("\n").replace(/^\n+/, "");
  return [uses, rest];
}

if (process.argv[1] && resolve(process.argv[1]) === fileURLToPath(import.meta.url)) {
  writeFileSync(rustExamplesPath, renderRustExamples());
  console.log(rustExamplesPath);
}
